trigger:
  - main

pool:
  vmImage: windows-latest

# variables:
#   advancedsecurity.codeql.querysuite: security-extended
#   advancedsecurity.submittoadvancedsecurity: true

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "18.x"
    displayName: "Install Node.js"

  - script: |
      npm install
    displayName: "npm install"

  - task: AdvancedSecurity-Codeql-Init@1
    inputs:
      languages: 'javascript'
      querysuite: 'security-and-quality'

  - task: AdvancedSecurity-Dependency-Scanning@1

  # - task: AdvancedSecurity-Codeql-Autobuild@1
  - task: AdvancedSecurity-Codeql-Analyze@1

  # - task: AdvancedSecurity-Publish@1
